1.0 release blog and website changes
PixiEditor/PixiEditor.net pull request #20
Opened 2023-02-24 19:34 UTC by flabbet

- Updated landing and download page
- New 1.0 release blog post
- Removed shortcuts page (nobody uses version < 0.1.5 anyway)

@Equbuxu @CPKreuz please review blog post, I'm not sure about comparing other apps section, maybe it is unnecessary, tell me what do you think

2023-02-24 21:41 UTC, Equbuxu requested changes
"PixiEditor 1.0 is available" text isn't verically centered on smaller screens 
![image](https://user-images.githubusercontent.com/29402050/221295717-3b02677e-3a16-4ceb-9f63-9ddb670cabab.png)

I think the roast of inkscape is a bit too long, I'd keep just the part where the line you just drew isn't visible. And remove audacity too, the UI looking old is not objectively a bad thing (and it actually doesn't look old? it used to have a different design which actually looked like it came from win 95, right now it looks fairly modern imo).

2023-02-24 21:41 UTC, Equbuxu commented on website/blog/2023-02-27-1.0-release.mdx
> +We've listed some of the new stuff in [previous devlog](/blog/2022/07/04/devlog2), however, I'll describe all of them in short.
`listed some of the new stuff .. describe all of them` doesn't make sense

2023-02-24 21:41 UTC, Equbuxu commented on website/blog/2023-02-27-1.0-release.mdx
> +Selection now allows scaling and rotating (with pivot!). Maybe one day we'll add skewing too.
we have skewing and even perspective transform lol
try holding down ctrl and dragging one of the corner or side anchors

2023-02-25 11:03 UTC, flabbet commented on website/blog/2023-02-27-1.0-release.mdx
> +We've listed some of the new stuff in [previous devlog](/blog/2022/07/04/devlog2), however, I'll describe all of them in short.
> "PixiEditor 1.0 is available" text isn't verically centered on smaller screens ![image](https://user-images.githubusercontent.com/29402050/221295717-3b02677e-3a16-4ceb-9f63-9ddb670cabab.png)

It's not a problem imo

2023-02-25 11:19 UTC, flabbet commented on website/blog/2023-02-27-1.0-release.mdx
> +Selection now allows scaling and rotating (with pivot!). Maybe one day we'll add skewing too.
omg I love u

2023-02-27 17:23 UTC, merged