Blog/dynamic bitmaps
PixiEditor/PixiEditor.net pull request #3
Opened 2021-07-15 19:06 UTC by flabbet

2021-07-16 07:52 UTC, Equbuxu requested changes

2021-07-16 07:52 UTC, Equbuxu commented on website/blog/2021-07-15-dynamic-bitmaps.mdx
> +2. Wait for coordinates and color to apply
What do you mean by "to apply"

2021-07-16 07:52 UTC, Equbuxu commented on website/blog/2021-07-15-dynamic-bitmaps.mdx
> +  b. Else if new colored pixel X is smaller than 0 (relative to bitmap coordinates) or Y is smaller than 0, then increase the size to top left
Shouldn't there be four if's for each direction?

2021-07-16 07:52 UTC, Equbuxu commented on website/blog/2021-07-15-dynamic-bitmaps.mdx
> +It all depends on the implementation, platform, native bitmap APIs, etc.
What is "It all" referring to

2021-07-16 09:07 UTC, CPKreuz requested changes

2021-07-16 09:07 UTC, CPKreuz commented on website/blog/2021-07-15-dynamic-bitmaps.mdx
> +  <source src="/videos/dynamic-bitmaps.mp4" type="video/mp4"/>
Use a more up-to-date video

2021-07-16 14:54 UTC, flabbet commented on website/blog/2021-07-15-dynamic-bitmaps.mdx
> +  b. Else if new colored pixel X is smaller than 0 (relative to bitmap coordinates) or Y is smaller than 0, then increase the size to top left
Nope

2021-07-22 09:47 UTC, CPKreuz approved these changes

2021-07-22 14:48 UTC, merged